version: '2.2'

services:
  app:
    build: app/.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/itunes
    ports:
      - 7001:7001
    mem_limit: 256m
    links:
      - dev

  db:
    image: postgres:alpine
    ports:
      - "5401:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: itunes
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro

  dev:
    image: tianon/true
    restart: "no"
    depends_on:
      - db
